# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "GenSON" = super.buildPythonPackage {
    name = "GenSON-1.0.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/84/0dba142f2968e517a0ac0937245e2659150b7c9612ae4589130e36cf308c/genson-1.0.2.tar.gz";
      sha256 = "1yjn9k224dsmwgfypc7ir4v8198wcdghnfbzjl7y3gqcph42wvlb";
    };
  };
  "MarkupSafe" = super.buildPythonPackage {
    name = "MarkupSafe-1.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
  };
  "PyYAML" = super.buildPythonPackage {
    name = "PyYAML-5.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/65/837fefac7475963d1eccf4aa684c23b95aa6c1d033a2c5965ccb11e22623/PyYAML-5.1.1.tar.gz";
      sha256 = "0m89fz13lzxbd0vs9vf9d9w8l5h5rrqc08fsbpi2a913bqzlvfxl";
    };
  };
  "RESTinstance" = super.buildPythonPackage {
    name = "RESTinstance-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."GenSON"
      self."docutils"
      self."flex"
      self."jsonpath-ng"
      self."jsonschema"
      self."pygments"
      self."pytz"
      self."requests"
      self."rfc3987"
      self."robotframework"
      self."strict-rfc3339"
      self."tzlocal"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/a2/68a75d4e45d275047953f1295c837852b8d98afd75288ca29122ad595fb5/RESTinstance-1.0.0.tar.gz";
      sha256 = "1q15z4cvz86jkpvs9n229jsx6ai1znfwnnyxwblfsipp6nh8hsyd";
    };
  };
  "Send2Trash" = super.buildPythonPackage {
    name = "Send2Trash-1.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/2e/ea40de0304bb1dc4eb309de90aeec39871b9b7c4bd30f1a3cdcb3496f5c0/Send2Trash-1.5.0.tar.gz";
      sha256 = "1ci8vcwjmjlp11ljj1ckrfmml9fkq1mclx2gr53y4zvhgp01q030";
    };
  };
  "attrs" = super.buildPythonPackage {
    name = "attrs-19.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/d9/931a24cc5394f19383fbbe3e1147a0291276afa43a0dc3ed0d6cd9fda813/attrs-19.1.0.tar.gz";
      sha256 = "16g33zr5f449lqc5wgvzpknxryfzrfsxcr6kpgxwn7l5fkv71f7h";
    };
  };
  "backcall" = super.buildPythonPackage {
    name = "backcall-0.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz";
      sha256 = "1r01dqch3f8fdj3n6fviw8hxqrs6w5v0qw4izmvqzry1w9dxiv1q";
    };
  };
  "bleach" = super.buildPythonPackage {
    name = "bleach-3.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/5a/0df03e8735cd9c75167528299c738702437589b9c71a849489d00ffa82e8/bleach-3.1.0.tar.gz";
      sha256 = "1yhrgrhkln8bd6gn3imj69g1h4xqah9gaz9q26crqr6gmmvpzprz";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2019.6.16";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/67/5d0548226bcc34468e23a0333978f0e23d28d0b3f0c71a151aef9c3f7680/certifi-2019.6.16.tar.gz";
      sha256 = "159nhzjk8r98agk8p2130aygjcd2qc9lw84m2dxmg7qb7ak3npll";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "click" = super.buildPythonPackage {
    name = "click-7.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/5c/f60e9d8a1e77005f664b76ff8aeaee5bc05d0a91798afd7f53fc998dbc47/Click-7.0.tar.gz";
      sha256 = "1mzjixd4vjbjvzb6vylki9w1556a9qmdh35kzmq6cign46av952v";
    };
  };
  "decorator" = super.buildPythonPackage {
    name = "decorator-4.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/19/1119fe7b1e49b9c8a9f154c930060f37074ea2e8f9f6558efc2eeaa417a2/decorator-4.4.0.tar.gz";
      sha256 = "1pi54wqj2p6ka13x7q8d5zgqg9bcf7m5d00l7x5bi204qmhn65c6";
    };
  };
  "defusedxml" = super.buildPythonPackage {
    name = "defusedxml-0.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/5f/f8aa58ca0cf01cbcee728abc9d88bfeb74e95e6cb4334cfd5bed5673ea77/defusedxml-0.6.0.tar.gz";
      sha256 = "1xbp8fivl3wlbyg2jrvs4lalaqv1xp9a9f29p75wdx2s2d6h717n";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "entrypoints" = super.buildPythonPackage {
    name = "entrypoints-0.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b4/ef/063484f1f9ba3081e920ec9972c96664e2edb9fdc3d8669b0e3b8fc0ad7c/entrypoints-0.3.tar.gz";
      sha256 = "0lc4si3xb7hza424414rdqdc3vng3kcrph8jbvjqb32spqddf3f7";
    };
  };
  "flex" = super.buildPythonPackage {
    name = "flex-6.14.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."PyYAML"
      self."click"
      self."jsonpointer"
      self."requests"
      self."rfc3987"
      self."six"
      self."strict-rfc3339"
      self."validate-email"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/6f/6680594b2d34737b8cdf871e6216cd182d251d145297cb6805ddb4fd2502/flex-6.14.0.tar.gz";
      sha256 = "0qm3ylb10dxwmibj252dh4ryx7sq23ndyga3lckx3jj6abyal6kd";
    };
  };
  "future" = super.buildPythonPackage {
    name = "future-0.17.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz";
      sha256 = "1f2rlqn9rh7adgir52dlbqz69gsab44x0mlm8gf1cs7xvhv54137";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz";
      sha256 = "01rlkigdxg17sf9yar1jl8n18ls59367wqh59hnawlyg53vb6my3";
    };
  };
  "ipykernel" = super.buildPythonPackage {
    name = "ipykernel-5.1.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-client"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/94/415b5bb70410801a01ffb2e32e0371783033f4a92a3fb44d9ff50becb362/ipykernel-5.1.1.tar.gz";
      sha256 = "173nm29g85w8cac3fg40b27qaq26g41wgg6qn79ql1hq4w2n5sgh";
    };
  };
  "ipython" = super.buildPythonPackage {
    name = "ipython-7.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/bb/0ed1fb1d57d697326f9e9b827d9a74b81dee56031ed7c252bc716195ad7a/ipython-7.2.0.tar.gz";
      sha256 = "04nxpgv05qizmwcr5swbndaizbwsj4lbjshjxhfkyiknkch9d53a";
    };
  };
  "ipython-genutils" = super.buildPythonPackage {
    name = "ipython-genutils-0.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/69/fbeffffc05236398ebfcfb512b6d2511c622871dca1746361006da310399/ipython_genutils-0.2.0.tar.gz";
      sha256 = "1a4bc9y8hnvq6cp08qs4mckgm6i6ajpndp4g496rvvzcfmp12bpb";
    };
  };
  "ipywidgets" = super.buildPythonPackage {
    name = "ipywidgets-7.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."nbformat"
      self."traitlets"
      self."widgetsnbextension"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/53/93/708cdb1feda1ec2d55ee9357d319a92f4d9adb61e5822a323aac9a6af8e6/ipywidgets-7.5.0.tar.gz";
      sha256 = "18lg3qaq9yhmgr8pz6az99hzdaml7f112ms31b805adcfilkq9nb";
    };
  };
  "jedi" = super.buildPythonPackage {
    name = "jedi-0.14.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."parso"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0f/f9/2fd9da09a29c0b7db05c7f152651c5c54a4ef0549b6bc9be82f3019f7da5/jedi-0.14.1.tar.gz";
      sha256 = "0dmgx9c0f7yx897bf13nrp5gbgal192y44y5dhqcvkyklzqm1j2k";
    };
  };
  "jinja2" = super.buildPythonPackage {
    name = "jinja2-2.10.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/ea/d884a06f8c7f9b7afbc8138b762e80479fb17aedbbe2b06515a12de9378d/Jinja2-2.10.1.tar.gz";
      sha256 = "04shqrs56aj04ipyqykj512rw2l0zfammvj9krawzxz7xc14yp06";
    };
  };
  "json5" = super.buildPythonPackage {
    name = "json5-0.8.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/68/e182f2c6e8d672dbf368a06640ccfc0fb64ef181f721ec29c16d9c383f98/json5-0.8.5.tar.gz";
      sha256 = "1c3k5blbhq7g2lnbap26a846ag5x19ivisd3wfzz6bzdl46hyjqj";
    };
  };
  "jsonpath-ng" = super.buildPythonPackage {
    name = "jsonpath-ng-1.4.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."decorator"
      self."ply"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/f3/cd8f8a0bb345985b83e76721e6f64222f92f34a217a4e9720f70427a1b4c/jsonpath-ng-1.4.3.tar.gz";
      sha256 = "1gphkq565nq2bms9mha5gir9q38gzgfgnmd48mlg9cp9fyw7bz5i";
    };
  };
  "jsonpointer" = super.buildPythonPackage {
    name = "jsonpointer-2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/e7/246d9ef2366d430f0ce7bdc494ea2df8b49d7a2a41ba51f5655f68cfe85f/jsonpointer-2.0.tar.gz";
      sha256 = "0qjkjy1qlyc1nl3k95wd03ssxac0a717x8889ypgs1cfcj3bm4n1";
    };
  };
  "jsonschema" = super.buildPythonPackage {
    name = "jsonschema-3.0.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
      self."setuptools"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/7f/a020327823b9c405ee6f85ab3053ff171e10801b19cfe55c78bb0b3810e7/jsonschema-3.0.1.tar.gz";
      sha256 = "03g20i1xfg4qdlk4475pl4pp7y0h37g1fbgs5qhy678q9xb822hc";
    };
  };
  "jupyter" = super.buildPythonPackage {
    name = "jupyter-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."nbconvert"
      self."notebook"
      self."qtconsole"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/a9/371d0b8fe37dd231cf4b2cff0a9f0f25e98f3a73c3771742444be27f2944/jupyter-1.0.0.tar.gz";
      sha256 = "0pwf3pminkzyzgx5kcplvvbvwrrzd3baa7lmh96f647k30rlpp6r";
    };
  };
  "jupyter-client" = super.buildPythonPackage {
    name = "jupyter-client-5.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/90/314cb3c69f25e70f82ba8528e536fbe66510daff83f22ef3f22082986a9e/jupyter_client-5.3.1.tar.gz";
      sha256 = "102qgc7isfxwq0zsj6m9apcyj2hk8c8c4fz7656lxlpmvxgazs4q";
    };
  };
  "jupyter-console" = super.buildPythonPackage {
    name = "jupyter-console-6.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."prompt-toolkit"
      self."pygments"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/c8/b7e768a3dec19b09d8ad5296a479e03c19a741a1bb4abab27c09236b8562/jupyter_console-6.0.0.tar.gz";
      sha256 = "1xdjw11cppf1fxvwkw2bk13ckkwas3bdah8baingn9296mvfi31h";
    };
  };
  "jupyter-core" = super.buildPythonPackage {
    name = "jupyter-core-4.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/de/ff4ca734656d17ebe0450807b59d728f45277e2e7f4b82bc9aae6cb82961/jupyter_core-4.5.0.tar.gz";
      sha256 = "1xr4pbghwk5hayn5wwnhb7z95380r45p79gf5if5pi1akwg7qvic";
    };
  };
  "jupyterlab" = super.buildPythonPackage {
    name = "jupyterlab-1.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyterlab-server"
      self."notebook"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/28/7fa6996b0f8a123f58fa92ab9868029020df01a821ccdd8037df258984aa/jupyterlab-1.0.2.tar.gz";
      sha256 = "0ghr4fqmg3w42417jyff0fdv90c71crm0bpgzmra28z7sjb61ap8";
    };
  };
  "jupyterlab-server" = super.buildPythonPackage {
    name = "jupyterlab-server-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."json5"
      self."jsonschema"
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/37/ecdeace2c358a78dff7fd35de4c8b43dcc617532f55fc218698cfe6f21ec/jupyterlab_server-1.0.0.tar.gz";
      sha256 = "06hsyk0nrikcmqgv3l29bhgdmvdls1d9bfdwnl1pvxwkizp66zm7";
    };
  };
  "lunr" = super.buildPythonPackage {
    name = "lunr-0.5.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."future"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/3b/9ad891da3ba78d43ee90104cd2126a032ec8b0088526be4327ffa06eedf5/lunr-0.5.5.tar.gz";
      sha256 = "0w3mypj8m6y5ii0vj01p6g0s492gy8ymxv2yn25klnc1cxa65yn5";
    };
  };
  "mistune" = super.buildPythonPackage {
    name = "mistune-0.8.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/a4/509f6e7783ddd35482feda27bc7f72e65b5e7dc910eca4ab2164daf9c577/mistune-0.8.4.tar.gz";
      sha256 = "0vkmsh0x480rni51lhyvigfdf06b9247z868pk3bal1wnnfl58sr";
    };
  };
  "nbconvert" = super.buildPythonPackage {
    name = "nbconvert-5.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."bleach"
      self."defusedxml"
      self."entrypoints"
      self."jinja2"
      self."jupyter-core"
      self."mistune"
      self."nbformat"
      self."pandocfilters"
      self."pygments"
      self."testpath"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/83/28b80ccd628e96e613763facc0281ae8bae957a87673445db496de26dab7/nbconvert-5.5.0.tar.gz";
      sha256 = "1763li336y20sh5xv7bxygqwq06873yfrkxmb525i0qxljx830qk";
    };
  };
  "nbformat" = super.buildPythonPackage {
    name = "nbformat-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/0e/160754f7ae3e984863f585a3743b0ed1702043a81245907c8fae2d537155/nbformat-4.4.0.tar.gz";
      sha256 = "00nlf08h8yc4q73nphfvfhxrcnilaqanb8z0mdy6nxk0vzq4wjgp";
    };
  };
  "notebook" = super.buildPythonPackage {
    name = "notebook-5.7.8";
    doCheck = false;
    propagatedBuildInputs = [
      self."Send2Trash"
      self."ipykernel"
      self."ipython-genutils"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/7a/b303380d3acd55ed906ddcf05782042940c3e8c05962295b26387ef2b37c/notebook-5.7.8.tar.gz";
      sha256 = "1f3f0m7vdb0qnhax5qbxhh01scmz45nvlr75nqc6pmy5a3k0lgjp";
    };
  };
  "pandocfilters" = super.buildPythonPackage {
    name = "pandocfilters-1.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz";
      sha256 = "1a8d9b7s48gmq9zj0pmbyv2sivn5i7m6mybgpkk4jm5vd7hp1pdk";
    };
  };
  "parso" = super.buildPythonPackage {
    name = "parso-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/40/615957db4d178b7504c87b1a5b85fa5945b0b4fa5f5a845e31fc7aad6018/parso-0.5.1.tar.gz";
      sha256 = "171a9ivhxwsd52h1cgsz40zgzpgzscn7yqb7sdjhy8m1lzj0wsv6";
    };
  };
  "pexpect" = super.buildPythonPackage {
    name = "pexpect-4.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/b1/362a0d4235496cb42c33d1d8732b5e2c607b0129ad5fdd76f5a583b9fcb3/pexpect-4.7.0.tar.gz";
      sha256 = "1sv2rri15zwhds85a4kamwh9pj49qcxv7m4miyr4jfpfwv81yb4y";
    };
  };
  "pickleshare" = super.buildPythonPackage {
    name = "pickleshare-0.7.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/b6/df3c1c9b616e9c0edbc4fbab6ddd09df9535849c64ba51fcb6531c32d4d8/pickleshare-0.7.5.tar.gz";
      sha256 = "1jmghg3c53yp1i8cm6pcrm280ayi8621rwyav9fac7awjr3kss47";
    };
  };
  "pillow" = super.buildPythonPackage {
    name = "pillow-6.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/fe/18125dc680720e4c3086dd3f5f95d80057c41ab98326877fc7d3ff6d0ee5/Pillow-6.1.0.tar.gz";
      sha256 = "1pnrsz0f0n0c819v1pdr8j6rm8xvhc9f3kh1fv9xpdp9n5ygf108";
    };
  };
  "ply" = super.buildPythonPackage {
    name = "ply-3.11";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/69/882ee5c9d017149285cab114ebeab373308ef0f874fcdac9beb90e0ac4da/ply-3.11.tar.gz";
      sha256 = "18qx113g9bi1ac4indd5phma82zcdq601lxncp3vjn43m2mc3iq0";
    };
  };
  "prometheus-client" = super.buildPythonPackage {
    name = "prometheus-client-0.7.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/23/41a5a24b502d35a4ad50a5bb7202a5e1d9a0364d0c12f56db3dbf7aca76d/prometheus_client-0.7.1.tar.gz";
      sha256 = "1ni2yv4ixwz32nz39ckia76lvggi7m19y5f702w5qczbnfi29kbi";
    };
  };
  "prompt-toolkit" = super.buildPythonPackage {
    name = "prompt-toolkit-2.0.9";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/a0/57dc47115621d9b3fcc589848cdbcbb6c4c130186e8fc4c4704766a7a699/prompt_toolkit-2.0.9.tar.gz";
      sha256 = "1hg32mayv5v9mwj5gyshfrmd2r03mlvj4dkhwz45zz9qh0fss695";
    };
  };
  "ptyprocess" = super.buildPythonPackage {
    name = "ptyprocess-0.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/2d/e4b8733cf79b7309d84c9081a4ab558c89d8c89da5961bf4ddb050ca1ce0/ptyprocess-0.6.0.tar.gz";
      sha256 = "1h4lcd3w5nrxnsk436ar7fwkiy5rfn5wj2xwy9l0r4mdqnf2jgwj";
    };
  };
  "pygments" = super.buildPythonPackage {
    name = "pygments-2.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/69/413708eaf3a64a6abb8972644e0f20891a55e621c6759e2c3f3891e05d63/Pygments-2.3.1.tar.gz";
      sha256 = "0ji87g09jph8jqcvclgb02qvxasdnr9pzvk90rl66d90yqcxmyjz";
    };
  };
  "pyrsistent" = super.buildPythonPackage {
    name = "pyrsistent-0.15.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/ef/7781092174a42d0b57fb02a2eb23f78ebc8e588c9bd7455e1d1c7b1ea516/pyrsistent-0.15.3.tar.gz";
      sha256 = "053yj6kdwz8z4xn7nj50nmkb9g3jj93jxk1dpvabk4fahyygxksh";
    };
  };
  "pytest-runner" = super.buildPythonPackage {
    name = "pytest-runner-5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/6d/4b41a74b31720e25abd4799be72d54811da4b4d0233e38b75864dcc1f7ad/pytest-runner-5.1.tar.gz";
      sha256 = "0ykfcnpp8c22winj63qzc07l5axwlc9ikl8vn05sc32gv3417815";
    };
  };
  "python-dateutil" = super.buildPythonPackage {
    name = "python-dateutil-2.8.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/99/5b2e99737edeb28c71bcbec5b5dda19d0d9ef3ca3e92e3e925e7c0bb364c/python-dateutil-2.8.0.tar.gz";
      sha256 = "17nsfhy4xdz1khrfxa61vd7pmvd5z0wa3zb6v4gb4kfnykv0b668";
    };
  };
  "pytz" = super.buildPythonPackage {
    name = "pytz-2018.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/be/6c59e30e208a5f28da85751b93ec7b97e4612268bb054d0dff396e758a90/pytz-2018.9.tar.gz";
      sha256 = "0k1pqnq3c4gvcspjxf3fschdjn71fk89i4wz801rxqh7f145xw6m";
    };
  };
  "pyzmq" = super.buildPythonPackage {
    name = "pyzmq-18.0.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/5e/7e4ed045fc1fb7667de4975fe8b6ab6b358b16bcc59e8349c9bd092931b6/pyzmq-18.0.2.tar.gz";
      sha256 = "1hkg0ack2i5y602zxhr901anmz6v8x2wj53yniip643kmhviv89i";
    };
  };
  "qtconsole" = super.buildPythonPackage {
    name = "qtconsole-4.5.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython-genutils"
      self."jupyter-client"
      self."jupyter-core"
      self."pygments"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/51/8b8164d588a148048a46e0d82d0335ff0b6530ff59bbb862acb49a01399b/qtconsole-4.5.1.tar.gz";
      sha256 = "1qhsw3dsi9d5y2g1vfi0g95sw8xv2zvmawljnawsc03gvnn4zy2a";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.21.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz";
      sha256 = "13jr0wkj9c2j8c0c8iaal9iivi0bpxghnsdn6lxcpnmc657q4ajh";
    };
  };
  "rfc3987" = super.buildPythonPackage {
    name = "rfc3987-1.3.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/bb/f1395c4b62f251a1cb503ff884500ebd248eed593f41b469f89caa3547bd/rfc3987-1.3.8.tar.gz";
      sha256 = "0cx7bhyjaylwnf9armxrkb3r0s37vf0vqf3bhbll9mb0lmbx5i6k";
    };
  };
  "robotframework" = super.buildPythonPackage {
    name = "robotframework-3.1.2";
    doCheck = false;
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/04/2aee0fb807e14d2f2463217f81ac94c542b5b0c5809a7535f284a0bbb05c/robotframework-3.1.2.zip";
      sha256 = "1g0d4fqmws3dp7mzkqf63cwvjcdpbmmh47nxh17jm5n7r30df3gi";
    };
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage {
    name = "robotframework-seleniumlibrary-3.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework"
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c8/e7/c577d9528b80d748fe7beca1b106d751caf39d0d77f8fd85e39b1ef50ded/robotframework-seleniumlibrary-3.3.1.tar.gz";
      sha256 = "03x1fbc37mb9lkm3spn21hiyij8c8gs20517sc89nkqa7yx0wfkg";
    };
  };
  "robotkernel" = super.buildPythonPackage {
    name = "robotkernel-0.12.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."ipykernel"
      self."ipywidgets"
      self."lunr"
      self."nbformat"
      self."pillow"
      self."pygments"
      self."robotframework"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/5e/4d0496a83d332dc52401851d59e6a37ea83121b064dc39f77dfdfa5bedb5/robotkernel-0.12.2.tar.gz";
      sha256 = "15zkn4i2xpxb55ivgvz583fm35m1p8hzfpmlsh0i478mfl3nq7n0";
    };
  };
  "selenium" = super.buildPythonPackage {
    name = "selenium-3.141.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/9c/9030520bf6ff0b4c98988448a93c04fcbd5b13cd9520074d8ed53569ccfe/selenium-3.141.0.tar.gz";
      sha256 = "039hf9knvl4s3hp21bzwsp1g5ri9gxsh504dp48lc6nr1av35byy";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-41.0.1";
    doCheck = false;
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/64/a18a487b4391a05b9c7f938b94a16d80305bf0369c6b0b9509e86165e1d3/setuptools-41.0.1.zip";
      sha256 = "04sns22y2hhsrwfy1mha2lgslvpjsjsz8xws7h2rh5a7ylkd28m2";
    };
  };
  "setuptools-scm" = super.buildPythonPackage {
    name = "setuptools-scm-3.3.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/44/53cad68ce686585d12222e6769682c4bdb9686808d2739671f9175e2938b/setuptools_scm-3.3.3.tar.gz";
      sha256 = "19cyndx23xmpbhz4qrwmfwsmnnaczd0dw7qg977ksq2dbvxy29dx";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.12.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz";
      sha256 = "0wxs1q74v07ssjywbbm7x6h5v9qx209ld2yfsif4060sxi0h2sni";
    };
  };
  "strict-rfc3339" = super.buildPythonPackage {
    name = "strict-rfc3339-0.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz";
      sha256 = "0xqjbsn0g1h88rayh5yrpdagq60zfwrfs3yvk6rmgby3vyz1gbaw";
    };
  };
  "terminado" = super.buildPythonPackage {
    name = "terminado-0.8.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/fc/f5c7c36ac0da236078a26da7dce5748db45c8273cd551232ae01b26043b3/terminado-0.8.2.tar.gz";
      sha256 = "1hi05knmq1y9a1vpnbqv6gqc6nb2mfbv1v2hn2c0ffiwz10y226y";
    };
  };
  "testpath" = super.buildPythonPackage {
    name = "testpath-0.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/30/9a7e917066d851d8b4117e85794b5f14516419ea714a8a2681ec6aa8a981/testpath-0.4.2.tar.gz";
      sha256 = "1y40hywscnnyb734pnzm55nd8r8kp1072bjxbil83gcd53cv755n";
    };
  };
  "tornado" = super.buildPythonPackage {
    name = "tornado-6.0.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz";
      sha256 = "1afpxpv75zi1zvj2b3s6d7r4s4p0z2byh7jv9h3i4sb1p8vdnif8";
    };
  };
  "traitlets" = super.buildPythonPackage {
    name = "traitlets-4.3.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."decorator"
      self."ipython-genutils"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/98/7f5ef2fe9e9e071813aaf9cb91d1a732e0a68b6c44a32b38cb8e14c3f069/traitlets-4.3.2.tar.gz";
      sha256 = "0dbq7sx26xqz5ixs711k5nc88p8a0nqyz6162pwks5dpcz9d4jww";
    };
  };
  "tzlocal" = super.buildPythonPackage {
    name = "tzlocal-1.5.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz";
      sha256 = "0kiciwiqx0bv0fbc913idxibc4ygg4cb7f8rcpd9ij2shi4bigjf";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.24.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/3c/1bb7ef6c435dea026f06ed9f3ba16aa93f9f4f5d3857a51a35dfa00882f1/urllib3-1.24.3.tar.gz";
      sha256 = "1x0slqrv6kixkbcdnxbglvjliwhc1payavxjvk8fvbqjrnasd4r3";
    };
  };
  "validate-email" = super.buildPythonPackage {
    name = "validate-email-1.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/a0/cb53fb64b52123513d04f9b913b905f3eb6fda7264e639b4573cc715c29f/validate_email-1.3.tar.gz";
      sha256 = "1bxffaf5yz2cph8ki55vdvdypbwkvn2xr1firlcy62vqbzf1jivq";
    };
  };
  "wcwidth" = super.buildPythonPackage {
    name = "wcwidth-0.1.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz";
      sha256 = "0pn6dflzm609m4r3i8ik5ni9ijjbb5fa3vg1n7hn6vkd49r77wrx";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "widgetsnbextension" = super.buildPythonPackage {
    name = "widgetsnbextension-3.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/11/df627aeac1d8433e71b2dcb193392fed5e96b43903b39fa718a1918c6364/widgetsnbextension-3.5.0.tar.gz";
      sha256 = "11hz3rbwamkan46rl1s3wafxbf607hnl665yjr14iwl8wdrlv6wc";
    };
  };
}
